# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: /project
email: email@email.com
description: Tech &#8226; eSports &#8226; User stories
owner_name: "Omer Kaplan" #This appears on the title of the homepage
baseurl: "" # the subpath of your site, e.g. /blog *NOTE* This is differnt from local file dure to testing
url: "http://slashproject.co" # the base hostname & protocol *NOTE* This is differnt from local file due to testing
twitter_username: omerkaplan
github_username:  omerkaplan
github_repository_url: "https://github.com/omerkaplan/project"
img_share_default: "default.jpg"
google_analytics: "UA-101975344-1"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

#Sources
img_path_url: "/assets/img/" #main images path (header images)
img_path_url_post: "/post" #individual posts images path

feed:
  path: feed.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
