# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: /Project
email: email@email.com
description: Tech &#8226; eSports &#8226; User stories
owner_name: "Omer Kaplan" #This appears on the title of the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: omerkaplan
github_username:  omerkaplan
github_repository_url: "https://github.com/omerkaplan/blog"
img_share_default: "Default.jpg"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

#Sources
img_path_url: "/assets/img/"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
